export default {
  sex: [{
    value: "男"
  }, {
    value: "女"
  }],

  jobType: [{
    value: "待業"
  }, {
    value: "學生"
  }, {
    value: "資訊科技業"
  }, {
    value: "傳統製造業"
  }, {
    value: "工商服務業"
  }, {
    value: "一般服務業"
  }, {
    value: "文教傳播業"
  }, {
    value: "家庭主婦/主夫"
  }, {
    value: "軍人"
  }, {
    value: "退休"
  }],

  mostVehicle: [{
    value: "徒步"
  }, {
    value: "機車"
  }, {
    value: "公車"
  }, {
    value: "捷運"
  }, {
    value: "汽車"
  }],
  // 全台行政區唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷
  props: {
    multiple: true
  },
  options: [{
    value: '台北市',
    label: '台北市',
    children: [{
      value: '中正區',
      label: '中正區'
    }, {
      value: '大同區',
      label: '大同區',
    }, {
      value: '中山區',
      label: '中山區',
    }, {
      value: '松山區',
      label: '松山區',
    }, {
      value: '大安區',
      label: '大安區',
    }, {
      value: '萬華區',
      label: '萬華區',
    }, {
      value: '信義區',
      label: '信義區',
    }, {
      value: '士林區',
      label: '士林區',
    }, {
      value: '北投區',
      label: '北投區',
    }, {
      value: '內湖區',
      label: '內湖區',
    }, {
      value: '南港區',
      label: '南港區',
    }, {
      value: '文山區',
      label: '文山區',
    }]
  }, {
    value: '新北市',
    label: '新北市',
    children: [{
      value: '板橋區',
      label: '板橋區'
    }, {
      value: '新莊區',
      label: '新莊區'
    }, {
      value: '中和區',
      label: '中和區'
    }, {
      value: '永和區',
      label: '永和區'
    }, {
      value: '土城區',
      label: '土城區'
    }, {
      value: '樹林區',
      label: '樹林區'
    }, {
      value: '三峽區',
      label: '三峽區'
    }, {
      value: '鶯歌區',
      label: '鶯歌區'
    }, {
      value: '三重區',
      label: '三重區'
    }, {
      value: '蘆洲區',
      label: '蘆洲區'
    }, {
      value: '五股區',
      label: '五股區'
    }, {
      value: '泰山區',
      label: '泰山區'
    }, {
      value: '林口區',
      label: '林口區'
    }, {
      value: '八里區',
      label: '八里區'
    }, {
      value: '淡水區',
      label: '淡水區'
    }, {
      value: '三芝區',
      label: '三芝區'
    }, {
      value: '石門區',
      label: '石門區'
    }, {
      value: '金山區',
      label: '金山區'
    }, {
      value: '萬里區',
      label: '萬里區'
    }, {
      value: '汐止區',
      label: '汐止區'
    }, {
      value: '瑞芳區',
      label: '瑞芳區'
    }, {
      value: '貢寮區',
      label: '貢寮區'
    }, {
      value: '平溪區',
      label: '平溪區'
    }, {
      value: '雙溪區',
      label: '雙溪區'
    }, {
      value: '新店區',
      label: '新店區'
    }, {
      value: '深坑區',
      label: '深坑區'
    }, {
      value: '石碇區',
      label: '石碇區'
    }, {
      value: '坪林區',
      label: '坪林區'
    }, {
      value: '烏來區',
      label: '烏來區'
    }]
  }, {
    value: '桃園市',
    label: '桃園市',
    children: [{
      value: '桃園區',
      label: '桃園區'
    }, {
      value: '中壢區',
      label: '中壢區'
    }, {
      value: '平鎮區',
      label: '平鎮區'
    }, {
      value: '八德區',
      label: '八德區'
    }, {
      value: '楊梅區',
      label: '楊梅區'
    }, {
      value: '蘆竹區',
      label: '蘆竹區'
    }, {
      value: '大溪區',
      label: '大溪區'
    }, {
      value: '龍潭區',
      label: '龍潭區'
    }, {
      value: '龜山區',
      label: '龜山區'
    }, {
      value: '大園區',
      label: '大園區'
    }, {
      value: '觀音區',
      label: '觀音區'
    }, {
      value: '新屋區',
      label: '新屋區'
    }, {
      value: '復興區',
      label: '復興區'
    }]
  }, {
    value: '新竹市',
    label: '新竹市',
    children: [{
      value: '東區',
      label: '東區'
    }, {
      value: '北區',
      label: '北區',
    }, {
      value: '香山區',
      label: '香山區',
    }]
  }, {
    value: '台中市',
    label: '台中市',
    children: [{
      value: '中區',
      label: '中區'
    }, {
      value: '東區',
      label: '東區'
    }, {
      value: '南區',
      label: '南區'
    }, {
      value: '西區',
      label: '西區'
    }, {
      value: '北區',
      label: '北區'
    }, {
      value: '北屯區',
      label: '北屯區'
    }, {
      value: '西屯區',
      label: '西屯區'
    }, {
      value: '南屯區',
      label: '南屯區'
    }, {
      value: '太平區',
      label: '太平區'
    }, {
      value: '大里區',
      label: '大里區'
    }, {
      value: '霧峰區',
      label: '霧峰區'
    }, {
      value: '烏日區',
      label: '烏日區'
    }, {
      value: '豐原區',
      label: '豐原區'
    }, {
      value: '后里區',
      label: '后里區'
    }, {
      value: '石岡區',
      label: '石岡區'
    }, {
      value: '東勢區',
      label: '東勢區'
    }, {
      value: '新社區',
      label: '新社區'
    }, {
      value: '潭子區',
      label: '潭子區'
    }, {
      value: '大雅區',
      label: '大雅區'
    }, {
      value: '神岡區',
      label: '神岡區'
    }, {
      value: '大肚區',
      label: '大肚區'
    }, {
      value: '沙鹿區',
      label: '沙鹿區'
    }, {
      value: '龍井區',
      label: '龍井區'
    }, {
      value: '梧棲區',
      label: '梧棲區'
    }, {
      value: '清水區',
      label: '清水區'
    }, {
      value: '大甲區',
      label: '大甲區'
    }, {
      value: '外埔區',
      label: '外埔區'
    }, {
      value: '大安區',
      label: '大安區'
    }, {
      value: '和平區',
      label: '和平區'
    }]
  }, {
    value: '台南市',
    label: '台南市',
    children: [{
      value: '中西區',
      label: '中西區'
    }, {
      value: '東區',
      label: '東區'
    }, {
      value: '南區',
      label: '南區'
    }, {
      value: '北區',
      label: '北區'
    }, {
      value: '安平區',
      label: '安平區'
    }, {
      value: '安南區',
      label: '安南區'
    }, {
      value: '永康區',
      label: '永康區'
    }, {
      value: '歸仁區',
      label: '歸仁區'
    }, {
      value: '新化區',
      label: '新化區'
    }, {
      value: '左鎮區',
      label: '左鎮區'
    }, {
      value: '玉井區',
      label: '玉井區'
    }, {
      value: '楠西區',
      label: '楠西區'
    }, {
      value: '南化區',
      label: '南化區'
    }, {
      value: '仁德區',
      label: '仁德區'
    }, {
      value: '關廟區',
      label: '關廟區'
    }, {
      value: '龍崎區',
      label: '龍崎區'
    }, {
      value: '官田區',
      label: '官田區'
    }, {
      value: '麻豆區',
      label: '麻豆區'
    }, {
      value: '佳里區',
      label: '佳里區'
    }, {
      value: '西港區',
      label: '西港區'
    }, {
      value: '七股區',
      label: '七股區'
    }, {
      value: '將軍區',
      label: '將軍區'
    }, {
      value: '學甲區',
      label: '學甲區'
    }, {
      value: '北門區',
      label: '北門區'
    }, {
      value: '新營區',
      label: '新營區'
    }, {
      value: '後壁區',
      label: '後壁區'
    }, {
      value: '白河區',
      label: '白河區'
    }, {
      value: '東山區',
      label: '東山區'
    }, {
      value: '六甲區',
      label: '六甲區'
    }, {
      value: '下營區',
      label: '下營區'
    }, {
      value: '柳營區',
      label: '柳營區'
    }, {
      value: '鹽水區',
      label: '鹽水區'
    }, {
      value: '善化區',
      label: '善化區'
    }, {
      value: '大內區',
      label: '大內區'
    }, {
      value: '山上區',
      label: '山上區'
    }, {
      value: '新市區',
      label: '新市區'
    }, {
      value: '安定區',
      label: '安定區'
    }]
  }, {
    value: '高雄市',
    label: '高雄市',
    children: [{
      value: '楠梓區',
      label: '楠梓區'
    }, {
      value: '左營區',
      label: '左營區'
    }, {
      value: '鼓山區',
      label: '鼓山區'
    }, {
      value: '三民區',
      label: '三民區'
    }, {
      value: '鹽埕區',
      label: '鹽埕區'
    }, {
      value: '前金區',
      label: '前金區'
    }, {
      value: '新興區',
      label: '新興區'
    }, {
      value: '苓雅區',
      label: '苓雅區'
    }, {
      value: '前鎮區',
      label: '前鎮區'
    }, {
      value: '旗津區',
      label: '旗津區'
    }, {
      value: '小港區',
      label: '小港區'
    }, {
      value: '鳳山區',
      label: '鳳山區'
    }, {
      value: '大寮區',
      label: '大寮區'
    }, {
      value: '鳥松區',
      label: '鳥松區'
    }, {
      value: '林園區',
      label: '林園區'
    }, {
      value: '仁武區',
      label: '仁武區'
    }, {
      value: '大樹區',
      label: '大樹區'
    }, {
      value: '大社區',
      label: '大社區'
    }, {
      value: '岡山區',
      label: '岡山區'
    }, {
      value: '路竹區',
      label: '路竹區'
    }, {
      value: '橋頭區',
      label: '橋頭區'
    }, {
      value: '梓官區',
      label: '梓官區'
    }, {
      value: '彌陀區',
      label: '彌陀區'
    }, {
      value: '永安區',
      label: '永安區'
    }, {
      value: '燕巢區',
      label: '燕巢區'
    }, {
      value: '田寮區',
      label: '田寮區'
    }, {
      value: '阿蓮區',
      label: '阿蓮區'
    }, {
      value: '茄萣區',
      label: '茄萣區'
    }, {
      value: '湖內區',
      label: '湖內區'
    }, {
      value: '旗山區',
      label: '旗山區'
    }, {
      value: '美濃區',
      label: '美濃區'
    }, {
      value: '內門區',
      label: '內門區'
    }, {
      value: '杉林區',
      label: '杉林區'
    }, {
      value: '甲仙區',
      label: '甲仙區'
    }, {
      value: '六龜區',
      label: '六龜區'
    }, {
      value: '茂林區',
      label: '茂林區'
    }, {
      value: '桃源區',
      label: '桃源區'
    }, {
      value: '那瑪夏區',
      label: '那瑪夏區'
    }]
  }, {
    value: '基隆市',
    label: '基隆市',
    children: [{
      value: '仁愛區',
      label: '仁愛區'
    }, {
      value: '中正區',
      label: '中正區'
    }, {
      value: '信義區',
      label: '信義區'
    }, {
      value: '中山區',
      label: '中山區'
    }, {
      value: '安樂區',
      label: '安樂區'
    }, {
      value: '暖暖區',
      label: '暖暖區'
    }, {
      value: '七堵區',
      label: '七堵區'
    }]
  }, {
    value: '嘉義市',
    label: '嘉義市',
    children: [{
      value: '東區',
      label: '東區'
    }, {
      value: '西區',
      label: '西區'
    }]
  }],

  // 全台行政區唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷唷

  mostPayWay: [{
    value: "現金"
  }, {
    value: "信用卡"
  }, {
    value: "悠遊卡"
  }, {
    value: "行動支付"
  }],

  mostBuyPlace: [{
    value: "超商"
  }, {
    value: "超市"
  }, {
    value: "百貨"
  }],

  avgGetupTime: [{
    value: "00:00~1:59"
  }, {
    value: "2:00~3:59"
  }, {
    value: "4:00~5:59"
  }, {
    value: "6:00~7:59"
  }, {
    value: "8:00~9:59"
  }, {
    value: "10:00~11:59"
  }, {
    value: "12:00~13:59"
  }, {
    value: "14:00~16:59"
  }, {
    value: "17:00~18:59"
  }, {
    value: "19:00~20:59"
  }, {
    value: "21:00~22:59"
  }, {
    value: "23:00~00:59"
  }],
  avgSleepTime: [{
    value: "00:00~1:59"
  }, {
    value: "2:00~3:59"
  }, {
    value: "4:00~5:59"
  }, {
    value: "6:00~7:59"
  }, {
    value: "8:00~9:59"
  }, {
    value: "10:00~11:59"
  }, {
    value: "12:00~13:59"
  }, {
    value: "14:00~16:59"
  }, {
    value: "17:00~18:59"
  }, {
    value: "19:00~20:59"
  }, {
    value: "21:00~22:59"
  }, {
    value: "23:00~00:59"
  }],
  avgOutTime: [{
    value: "00:00~1:59"
  }, {
    value: "2:00~3:59"
  }, {
    value: "4:00~5:59"
  }, {
    value: "6:00~7:59"
  }, {
    value: "8:00~9:59"
  }, {
    value: "10:00~11:59"
  }, {
    value: "12:00~13:59"
  }, {
    value: "14:00~16:59"
  }, {
    value: "17:00~18:59"
  }, {
    value: "19:00~20:59"
  }, {
    value: "21:00~22:59"
  }, {
    value: "23:00~00:59"
  }],
  avgHomeTime: [{
    value: "00:00~1:59"
  }, {
    value: "2:00~3:59"
  }, {
    value: "4:00~5:59"
  }, {
    value: "6:00~7:59"
  }, {
    value: "8:00~9:59"
  }, {
    value: "10:00~11:59"
  }, {
    value: "12:00~13:59"
  }, {
    value: "14:00~16:59"
  }, {
    value: "17:00~18:59"
  }, {
    value: "19:00~20:59"
  }, {
    value: "21:00~22:59"
  }, {
    value: "23:00~00:59"
  }],

  lifeUpdate: [{
    value: "0~1周"
  }, {
    value: "1~2周"
  }, {
    value: "2~3周"
  }, {
    value: "1個月"
  }, {
    value: "1~2個月"
  }, {
    value: ">2個月以上"
  }],

  mostUseApp: [{
    value: "運動類"
  }, {
    value: "健康類"
  }, {
    value: "購物類"
  }, {
    value: "娛樂類"
  }, {
    value: "教育類"
  }, {
    value: "攝影類"
  }, {
    value: "旅行類"
  }, {
    value: "社交類"
  }, {
    value: "金融類"
  }],

  "sportAppUseTime": "2",
  "healthAppUseTime": "2",
  "shoppingAppUseTime": "2",
  "entertainmentAppUseTime": "2",
  "educationAppUseTime": "2",
  "photoAppUseTime": "2",
  "travelAppUseTime": "2",
  "socialAppUseTime": "2",
  "finaceAppUseTime": "2"
}